### ISSUE TITLE
When time is decimal, the precision sometime goes up to 16

### ISSUE THREAD

**Issue by kvistgaard** [fbgallet/roam-extension-elapsed-time#1]
Example

![image](https://github.com/fbgallet/roam-extension-elapsed-time/assets/7572721/d3a75721-851e-49be-bab0-ab294b42e9e5)

It should be either rounded to 2, or configurable.

![image](https://github.com/fbgallet/roam-extension-elapsed-time/assets/7572721/3f8ee1ca-1152-4f5c-a326-aa5a12fd4fa2)

**Comment by fbgallet** [comment]
Strange enough, decimals should already [rounded to 2](https://github.com/fbgallet/roam-extension-elapsed-time/blob/6a9d45dfeccef86c4f1d4d1ee2c949d302993dd6/src/util.js#L269).
I will investigate.

**Comment by fbgallet** [comment]
Ok, I've found the issue, the total was not rounded (while the added numbers are... still a strange JS behavior)

**Comment by fbgallet** [comment]
The issue is fixed, the update will be submitted for review now.
